
- name: "Stopping Grafana Container"
  community.docker.docker_container:
   name: grafana
   state: absent
   container_default_behavior: compatibility
- name: "Stopping InfluxDB Container"
  community.docker.docker_container:
   name: influxdb
   state: absent
   container_default_behavior: compatibility
- name: "Stopping Telegraf Container"
  community.docker.docker_container:
   name: telegraf
   state: absent
   container_default_behavior: compatibility
- name: "Removing all Images"
  shell: "sh files/remove_images.sh"