- name: "Start Telegraf Container"
  community.docker.docker_container:
   name: telegraf
   image: telegraf:1.19.1
   state: started
   container_default_behavior: compatibility
   # auto_remove: no
   # detach: yes
   # init: no
   # interactive: yes
   # paused: no
   privileged: yes
   # read_only: no
   # tty: yes